#!/bin/bash

if [ $(id -u) != "0" ]; then
    echo "请使用管理员权限执行脚本！"
    exit
fi

wget http://download.navicat.com.cn/download/navicat121_premium_cs_x64.tar.gz
tar -zxvf navicat121_premium_cs_x64.tar.gz
sed -i 's|export LANG="en_US.UTF-8"|export LANG="zh_CN.UTF-8"|' navicat121_premium_cs_x64/start_navicat
cat << EOF > navicat121_premium_cs_x64/starts
#!/bin/sh
if [ ! -d ~/.navicat64 ];
then
 rm -r ~/.navicat64
fi
./start_navicat
EOF

## 安装配置
Install(){
mv navicat121_premium_cs_x64 /usr/local/navicat
mv resources/navicat-premium.svg /usr/share/icons/hicolor/scalable/apps
sudo -i
cat << EOF > /usr/share/applications/navicat_premium.desktop
[Desktop Entry]
Type=Application
Name=Navicat Premium
Comment=Navicat Premium
Icon=/usr/share/icons/hicolor/scalable/apps/navicat-premium.svg
Exec=/usr/local/navicat/start
Categories=Application;Development;
Terminal=false
StartupNotify=true
EOF
exit
}

Install
